version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rotascope_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rotascope
      MYSQL_USER: rotascope_user
      MYSQL_PASSWORD: rotascope_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - rotascope_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rotascope_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: rotascope
      DB_USER: rotascope_user
      DB_PASSWORD: rotascope_password
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - rotascope_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rotascope_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rotascope_network

volumes:
  mysql_data:

networks:
  rotascope_network:
    driver: bridge
